services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    ports:
      - "80:80"
    container_name: app
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./_docker/env/postgre.env
    ports:
      - "5432:5432"
    container_name: app_db
  redis:
    image: redis:7.2
    volumes:
      - ./tmp/redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6380:6379'
    restart: always
    container_name: app_redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    container_name: app_mailhoog
